/* eslint-disable quotes */

import tracery from 'tracery-grammar'

export const actionString = (boba: string) => {
  return `You drink ${boba}.`
}

export const generate = () => {
  var grammar = tracery.createGrammar({
    origin: [
      "#refreshing.a# #powerup# potion with #boba#"
    ],
    refreshing: [
      'refreshing',
      'tasty',
      'delicious',
      'lovely',
      'incredible',
      'delectable',
      'wonderfully #refreshing#', // learning a few years ago that you can recurse grammars like this makes me too powerful - kawa
      '#flavor#-flavored'
    ],
    flavor: [
      'banana',
      'orange',
      'lychee',
      'strawberry',
      'mango',
      'peach',
      'elderberry',
      'haskap berry',
      'almond',
      'cherry',
      'green tea',
      'chai',
      'oolong',
      'black tea',
      'ambrosia', // mostly positive but a few weirdos down here, which are all roguelike references - kawa
      'choko',
      'Gros Michel banana',
      'slime mold',
      'cheap imitation Amulet of Yendor',
      'starapple'
    ],
    powerup: [
      'blindness',
      'confusion',
      'detect monster',
      'detect things',
      'extra healing',
      'hallucination',
      'haste self',
      'healing',
      'increase strength',
      'levitation',
      'poison',
      'raise level',
      'restore strength',
      'see invisible',
      'torment',
      'brilliance',
      'Amulet seeking',
      'Speak With Eels',
      'intoxication',
      'fire breath',
      'ice breath',
      'entirely normal breath',
      'levitation',
      'enlightenment',
      'brown',
      'red',
      'white',
      'blue',
      'green',
      'yellow',
      'purple',
      'orange',
      'obsidian',
      'deep',
      'whimsy goddess',
      'lord\'s wrath',
      'spicy',
      'lovely jubbly',
      'skullduggery',
      'occult',
      'permadeath',
      'procedural',
      'rogue light',
      'loose lips',
      'expensive',
      'love',
      'archeologist',
      'barbarian',
      'healer',
      'knight',
      'monk',
      'priestess',
      'ranger',
      'rogue',
      'samurai',
      'tourist',
      'valkyrie',
      'wizard',
      'meat',
      'mana',
      'superior mana',
      'gingerbread',
      'pumpkin spice',
      'sewer brew',
      'battle readiness',
      'copycat ability',
      'soft hair',
      'knowing labyrinths',
      'high rolls',
      'RNG',
      '100 sided',
      'stinky presence',
      'temporary charisma',
      'curse',
      'ice cream',
      'daisy',
      'lilac',
      'rose',
      'tulip',
      'charm',
      'INT seed',
      'AGL seed',
      'STAM seed',
      'LCK seed',
      'sexy',
      'mathematics',
      'vampire\'s thrall',
      'square',
      'triangle',
      'sphere',
      'cube',
      'icosahedron',
      'iron skin',
      'golden touch',
      'giant growth',
      'hyper',
      'lightfoot',
      'featherfall',
      'magic missile',
      'athleticism',
      'spider climb',
      'neurosis',
      'disco',
      'performance',
      'natural history',
      'beast hide',
      'rage',
      'fear',
      'sleeping',
      'paralysis',
      'dwarf skin',
      'ice breath',
      'lightning touch',
      'necro',
      'raise dead',
      'escape rope',
      'stone gaze',
      'reflect',
      'barrier',
      'thorns aura',
      'water breathing',
      'luck',
      'fortune',
      'destiny',
      'foresight',
      'death',
      'instant death',
      'multiplayer',
      'call for help',
      'increase ability',
      'ability point',
      '+1',
      'fortitude',
      'mental fortitude',
      'stealth',
      'cloaking',
      'cacophony',
      'endurance',
      'polymorph',
      'swimming',
      'autosave',
      'rage quit',
      'session scheduling',
      'bludgeoning',
      'piercing',
      'shadow',
      'blessings',
      'angelic favor',
      'demonic favor',
      'dimensional travel',
      'avatar form',
      'force',
      'speak with animals',
      'truth',
      'nocturnal',
      'pickpocket',
      'intimidation',
      'invisibility',
      'trance',
      'mystic bond',
      'moon',
      'sun',
      'deep sea',
      'wanderlust',
      'royalty',
      'street urchin',
      'disguise',
      'poisoned kiss',
      'quenching',
      'doom',
      'culture',
      'riddle',
      'pizza',
      'madness',
      'TinyMedal',
      'Estus',
      'comestible',
      'Bumpblade',
      'Unterzee',
      'fizzy lifting',
      'Heart of the Cards',
      'creepypasta',
      'octarine'
    ],
    boba: [
      'Tapioca Pearls',
      'Mana Crystals',
      'Health Crystals',
      'Popping Crystals',
      'Ponderous Orbs',
      'Frog\'s Eyes',
      'Jester\'s Bells',
      'Newt\'s Eyes',
      'Lychee Jelly',
      'Stinky Durian Jelly',
      'Dragonfruit Jelly',
      'Strawberry Jelly',
      'Eel Jelly',
      'Jack O\'Lanterns',
      'Shadow Balls',
      'Mini Corndogs',
      'Murky Bubbles',
      'Freeze Dried Ice Cream',
      'Mini Chocolate Chips',
      'Lizard Eyes',
      'Coffee Grounds',
      'Man O\' War Jellies',
      'Cheese Curds',
      'Dimple Cup Spores',
      'Evil Eye Boba',
      'Popping Boba',
      'Popping Kobold Eyes',
      'Cave Spider Eggs',
      'Salmonid Roe',
      'Olives',
      'Marrow Dust',
      'Pixie Wing',
      'Pixie Dust',
      'Sticky Rice',
      'Mummy Dust',
      'Heart Candies',
      'Tentacle Cups',
      'Seaweed Sprinkles',
      'Boba',
      'Root Beer Barrels',
      'Pineapple Jelly',
      'Mana Fizzies',
      'Health Fizzies',
      'Gold Flecks',
      'Egg Whites',
      'Earth Crystals',
      'Wind Crystals',
      'Fire Crystals',
      'Shaved Ice',
      'Melon Jellies',
      'Vampire Tears',
      'King\'s Tears',
      'Forest Wisps',
      'Extra Carbonation',
      'Underwhelming Carbonation',
      'Thorns Boba',
      'Flame Jelly',
      'Vanilla Spackle',
      'Taro Boba',
      'Green Tea Leaves',
      'Butter Balls',
      'Mango Jelly',
      'Eel Jelly',
      'Leather Scraps',
      'Phoenix Down',
      '#flavor# bits',
      'whipped cream and #boba#'
    ]
  })

  grammar.addModifiers(tracery.baseEngModifiers)
  return grammar.flatten('#origin#')
}
/* eslint-enable quotes */
