/* eslint-disable quotes */

import tracery from 'tracery-grammar'

export const actionString = (drinkContent: string) => {
  return `${drinkContent}`
}

export const generate = () => {
  var grammar = tracery.createGrammar({
    origin: [
      "#liquid_sentence# #flavor_sentence#"
    ],
    liquid_sentence: [
      "Inside is #liquid.a#."
    ],
    liquid: [
      "#liquid_descriptor# #liquid_color# #liquid_type#",
      "#liquid_color# #liquid_type#"
    ],
    liquid_descriptor: [
      "clear",
      "cloudy",
      "thick",
      "viscous",
      "watery",
      "foul",
      "fragrant",
      "murky",
      "milky",
      "thin",
      "frothy",
      "bubbling"
    ],
    liquid_color: [
      "colorless",
      "blue",
      "cerulean",
      "red",
      "ruby",
      "yellow",
      "green",
      "chartreuse",
      "black",
      "grey",
      "white",
      "beige",
      "purple",
      "pink",
      "brown",
      "golden",
      "silvery"
    ],
    liquid_type: [
      "sludge",
      "liquid",
      "fluid",
      "bile",
      "vapor",
      "liquor",
      "solution",
      "juice",
      "spirit",
      "broth",
      "tincture",
      "gel",
      "mixture",
      "potion",
      "elixir",
      "mucous",
      "slush",
      "slime"
    ],
    flavor_sentence: [
      "The taste reminds you of #flavor# and #flavor#.",
      "It tastes vaguely of #flavor# and #flavor#, with a hint of #flavor#.",
      "It tastes like #flavor# and #flavor#, with notes of #flavor#."
    ],
    flavor: [
      "#flavor_real#",
      "#flavor_abstract#",
      "#flavor_fantastic#"
    ],
    flavor_real: [
      "coconut",
      "cucumber",
      "mango",
      "peach",
      "pear",
      "pineapple",
      "pomegranate",
      "pumpkin",
      "watermelon",
      "apple",
      "blackberry",
      "blueberry",
      "banana",
      "orange",
      "agave",
      "jalapeno",
      "tomato",
      "grape",
      "cherry",
      "milk",
      "egg",
      "oak",
      "peanut",
      "chocolate",
      "salt",
      "honey",
      "lavender",
      "mint",
      "elderflower",
      "ginger",
      "lemon",
      "lime",
      "basil",
      "hibiscus",
      "rosemary",
      "thyme",
      "oak",
      "licorice"
    ],
    flavor_abstract: [
      "revenge",
      "sorrow",
      "loneliness",
      "regret",
      "wrath",
      "pride",
      "angst",
      "longing",
      "nostalgia",
      "humility",
      "hubris",
      "blissfulness",
      "melancholy",
      "spite",
      "worship",
      "nightmares",
      "daydreams",
      "anxiety",
      "politeness",
      "classism",
      "mathematics",
      "disappointment",
      "revelation",
      "ancestry",
      "forgetfulness",
      "repetition",
      "randomness",
      "literature",
      "poetry",
      "justice",
      "lies",
      "truth",
      "knowledge",
      "apprehension",
      "rehearsal",
      "mythology",
      "if-statements",
      "gender",
      "eyesight",
      "publicity",
      "performance",
      "permadeath",
      "baseball",
      "astrology",
      "audio",
      "comedy",
      "postmodernism",
      "grammar",
      "sacrifice",
      "betrayal"
    ],
    flavor_fantastic: [
      "ambrosia",
      "gasoline",
      "beef",
      "chicken",
      "sand",
      "photons",
      "earwax",
      "toothpaste",
      "paper",
      "scissors",
      "caffeine",
      "ink",
      "tofu",
      "plastic",
      "seaweed",
      "toad",
      "ferns",
      "leather",
      "business cards",
      "candlewax",
      "money",
      "soap",
      "films",
      "homework",
      "crosswords",
      "web comics",
      "graphite",
      "podcasts",
      "typewriters",
      "potatoes",
      "dragonflies",
      "swamp",
      "disco",
      "meetings",
      "networking",
      "cat hair",
      "pasta"
    ]
  })

  grammar.addModifiers(tracery.baseEngModifiers)
  return grammar.flatten('#origin#')
}
/* eslint-enable quotes */
