/* eslint-disable quotes */

import tracery from 'tracery-grammar'

export const actionString = (drinkName: string) => {
  return `${drinkName}`
}

export const generate = () => {
  var grammar = tracery.createGrammar({
    origin: [
      "#name_adjective# #name_noun#",
      "#character#'s #name_noun#",
      "#name_adjective# #character#",
      "#name_noun# and #name_noun#",
      "#character# #character#"
    ],
    character: [
      "Aquator",
      "Bat",
      "Centaur",
      "Dragon",
      "Emu",
      "Flytrap",
      "Griffin",
      "Hobgoblin",
      "Ice Monster",
      "Jabberwock",
      "Kestrel",
      "Leprechaun",
      "Medusa",
      "Nymph",
      "Orc",
      "Phantom",
      "Quagga",
      "Rattlesnake",
      "Snake",
      "Troll",
      "Ur-VIle",
      "Vampire",
      "Xeroc",
      "Yeti",
      "Zombie",
      "Rogue",
      "Dragon",
      "Falcon",
      "Wanderer",
      "Demon",
      "Kobold",
      "Mage",
      "Warrior",
      "Shopkeep",
      "Lady",
      "Lion",
      "Monkey",
      "Horse",
      "Captain",
      "Bird",
      "Aunt",
      "Uncle",
      "Squirrel",
      "Cockatrice"
    ],
    name_adjective: [
      "Aqua",
      "Last",
      "Classic",
      "Salty",
      "Porcelain",
      "Alabaster",
      "Blue",
      "Green",
      "Brass",
      "Dirty",
      "Spicy",
      "Sea",
      "Gold",
      "Hot",
      "Paper",
      "Plain",
      "Smoked",
      "Dark",
      "Stormy",
      "Frozen",
      "Jungle",
      "Old",
      "Grand",
      "Prickly",
      "Bitter",
      "Golden",
      "Red",
      "Rusty",
      "Famous",
      "Pink",
      "Mini",
      "Fuzzy",
      "Deadly"
    ],
    name_noun: [
      "#rogue_noun#",
      "#non_noun#"
    ],
    rogue_noun: [
      "Nemesis",
      "Manor",
      "Sword",
      "Hack",
      "Tower",
      "Island",
      "Scarab",
      "Island",
      "Dungeon",
      "Revenge",
      "Castle",
      "Crystal",
      "Cave",
      "Labyrinth",
      "Thunderbolt",
      "World",
      "Cavern",
      "Domain",
      "Crawl",
      "Tale",
      "Dream",
      "Eye",
      "Doom",
      "Nightmare",
      "Adventure",
      "Seal",
      "Quest",
      "Star",
      "Amulet",
      "Fable",
      "Legacy",
      "Road",
      "Delve",
      "Fate",
      "Grift",
      "Loop",
      "Spire"
    ],
    non_noun: [
      "Sunrise",
      "Club",
      "Corpse",
      "Reviver",
      "Fizz",
      "Smash",
      "Word",
      "Dog",
      "Sling",
      "Breeze",
      "Bay",
      "Transfusion",
      "Kiss",
      "Potion",
      "Rush",
      "Tail",
      "Plane",
      "Revolver",
      "Mix",
      "Mama",
      "Sheet",
      "Punch",
      "Hurricane",
      "Sunset",
      "Mind",
      "Eraser",
      "Traincar",
      "Royale",
      "Blood",
      "Sand",
      "Pal",
      "Dream",
      "Connection",
      "Nail",
      "Stinger",
      "Afternoon",
      "Earthquake",
      "Tsunami",
      "Tornado",
      "Blizzard",
      "Sling",
      "Bramble",
      "Thorn",
      "Slammer",
      "Shoe",
      "Memory"
    ]
  })

  grammar.addModifiers(tracery.baseEngModifiers)
  return grammar.flatten('#origin#')
}
/* eslint-enable quotes */
