import tracery from 'tracery-grammar'

export const actionString = (game: string) => {
  return `Phwoop! A capsule shoots out of the tube! Unfurling the paper inside, it reads: ${game}.`
}

export const generate = () => {
  var grammar = tracery.createGrammar({
    origin: [
      '<a href="https://store.steampowered.com/app/1260590" target="_blank">Hadean Tactics</a></br></br>Hadean Tactics is a roguelike deckbuilding game fused with autobattler elements to create a unique strategy experience. Use your cards to influence the actions of your units and help your Hero defeat the Six Wings of Hell!',
      '<a href="https://store.steampowered.com/app/2085580" target="_blank">Strange Dungeon</a></br></br>Find allies, friends, or lovers as your crew explores, researches, and negotiates their way through this turn-based tactical roguelike about convincing cave monsters not to kill you. Make smart decisions to avoid vicious perils like nuclear meltdowns, panic attacks, and badly seasoned fish.',
      '<a href="https://store.steampowered.com/app/1394130" target="_blank">Breach Wanderers</a></br></br>Strategize through difficult battles in this new take on Roguelite Deckbuilders. Breach Wanderers lets you fine-tune your decks before each run, allowing for varied playstyles with many unique characters to choose from. Join our growing community to find exciting new deck ideas and share your own!',
      '<a href="https://store.steampowered.com/app/1452000" target="_blank">It\'s Six Random Characters and a Single Floor Dungeon, That\'s the Whole Game</a></br></br>A roguelike first-person dungeon crawler. Use a random party of six characters to get through a single dungeon.',
      '<a href="https://store.steampowered.com/app/1271280" target="_blank">Rift Wizard</a></br></br>Rift Wizard is a tough as nails fantasy roguelike featuring challenging turn based combat and deep open ended character building. Craft your spellbook from over 100 unique spells and abilities and fight your way through a series of procedurally generated challenges to defeat your nemesis.',
      '<a href="https://store.steampowered.com/app/943590" target="_blank">BlitzKeep Unleashed</a></br></br>BlitzKeep Unleashed, where billiards meets a roguelite RPG! Or maybe pinball meets an RPG? Something like that! Level up, defeat enemies and bosses, buy permanent upgrades and new classes, play local coop, and more in procedurally-generated dungeons across 10 realms and 40 levels.',
      '<a href="https://store.steampowered.com/app/1121640" target="_blank">The Wandering Village</a></br></br>The Wandering Village is a city-building simulation game on the back of a giant, wandering creature. Build your settlement and form a symbiotic relationship with the colossus. Will you survive together in this hostile, yet beautiful post-apocalyptic world, contaminated by poisonous plants?',
      '<a href="https://store.steampowered.com/app/1835240" target="_blank">Spiritfall</a></br></br>Spiritfall is a fast-paced Action Roguelite with combat inspired by Platform Fighters. Slash, smash, launch, and wall-splat a multitude of enemies using an ever-changing arsenal of divine powers.',
      '<a href="https://store.steampowered.com/app/364510" target="_blank">Transcendence</a></br></br>Explore the farthest reaches of Human Space in this open-world space adventure. Compelled to journey to the Galactic Core by a mysterious hyperintelligence, you must fight your way through dozens of star systems teeming with clashing empires, expansionist AIs, and fearsome xenophobes.',
      '<a href="https://store.steampowered.com/app/1102190" target="_blank">Monster Train</a></br></br>Monster Train is a strategic roguelike deck building game with a twist. Set on a train to hell, you’ll use tactical decision making to defend multiple vertical battlegrounds. With real time competitive multiplayer and endless replayability, Monster Train is always on time.',
      '<a href="https://store.steampowered.com/app/333640" target="_blank">Caves of Qud</a></br></br>Caves of Qud is a science fantasy roguelike epic steeped in retrofuturism, deep simulation, and swathes of sentient plants. Come inhabit an exotic world and chisel through layers of thousand-year-old civilizations.',
      '<a href="https://store.steampowered.com/app/561740" target="_blank">MidBoss</a></br></br>Kill your enemies, possess their bodies, and take their abilities as your own in this turn-based procedurally generated death labyrinth.',
      '<a href="https://store.steampowered.com/app/848030" target="_blank">Roundguard</a></br></br>Roundguard is a bouncy dungeon crawler with pinball physics, lots of loot, and a randomized castle full of oddballs. Press your luck against hordes of dangerously cute monsters and challenging roguelike elements in this all-round bouncy adventure!',
      '<a href="https://store.steampowered.com/app/1976950" target="_blank">Desktop Dungeons: Rewind</a></br></br>Desktop Dungeons: Rewind bestows bites of tactical roguelike action, which will quickly fester into a deep, lingering, and strategic obsession. Bargain with gods, equip your spoon and pick your battles, before retreating into the healing darkness. But beware… there are still many monsters to face!',
      '<a href="https://store.steampowered.com/app/1963010" target="_blank">Purgatory Dungeoneer</a></br></br>Purgatory Dungeoneer is a townbuilding roguelite RPG about plundering a psychic hellmaw for personal closure, and the resources to build a village beyond the grave.',
      '<a href="https://store.steampowered.com/app/1077450" target="_blank">Wally and the FANTASTIC PREDATORS</a></br></br>Your best friend wants to cheer you up, so he tries his best to make a dungeon for you to explore. Explore his wholesome, weird-as-heck, scrappy rogue-lite oozing with charm and humor for 1-2 Players.',
      '<a href="https://store.steampowered.com/app/1830430" target="_blank">Grimoire Groves</a></br></br>Become a masterful witch as you grow cute plant creatures with your magic in this cozy rogue-lite dungeon crawler. Craft powerful spells and items, discover new plant types, befriend magical creatures, and restore the magical forest.',
      '<a href="https://store.steampowered.com/app/288120" target="_blank">Dungeonmans</a></br></br>Crush monsters and get loots in the classic turn-based style of deep dungeons and high adventure! Grow the Dungeonmans Academy, a bastion of learning that expands as you play. Serious gameplay with a light-hearted atmosphere, combining the feel of history\'s great RPGs and dice-slinging adventures around the tabletop.',
      '<a href="https://store.steampowered.com/app/399720" target="_blank">XO</a></br></br>XO is a sci-fi real-time-with-pause strategy game inspired by FTL. Build a fleet and try to stay ahead of the relentless Harvesters. Each ship you add to your fleet gives you powers but also reduces your dwindling resources. Who will you choose to survive?',
      '<a href="https://store.steampowered.com/app/1373260" target="_blank">Obsidian Prince</a></br></br>Fight through dungeons in a tactical, turn-based roguelike where choices have real consequences. Recruit diverse heroes and steer them to their death... *ahem*... glory. Explore and rebuild the overworld to boost your heroes and discover hidden quests and new dungeons to master.',
      '<a href="https://store.steampowered.com/app/274700" target="_blank">868-HACK</a></br></br>You are a computer hacker. You steal precious data while the world sleeps.',
      '<a href="https://store.steampowered.com/app/1269300" target="_blank">This Means Warp</a></br></br>It’s co-op space survival fun, Jim, but not as we know it. This Means Warp is an intense spaceship management roguelite experience for 1-4 players. Explore a procedurally generated universe, upgrade your ship, battle dangerous enemies and adapt your strategies to survive in a hostile galaxy.',
      '<a href="https://store.steampowered.com/app/1668690" target="_blank">Alina of the Arena</a></br></br>A roguelike deckbuilding tactics game that combines elements from \'Slay the Spire\' and \'Into the Breach\'. Play as a gladiator to survive. With roguelike deckbuilding and hex-based tactics, no longer bound by simple attack and defense. Make use of dodges and knockbacks to stay alive!',
      '<a href="https://store.steampowered.com/app/1622800" target="_blank">Super Dungeon Maker</a></br></br>Super Dungeon Maker is a creative pixel art dungeon editor inspired by the best 2D adventure games. Choose however many levels, enemies, secret rooms, traps and items you want. Challenge your friends and the community to master your dungeon or play the countless dungeons of the community.',
      '<a href="https://store.steampowered.com/app/254320" target="_blank">Duskers</a></br></br>Pilot drones into derelict spaceships to find the means to survive and piece together how the universe became a giant graveyard.',
      '<a href="https://store.steampowered.com/app/1981370" target="_blank">Down the Drain</a></br></br>Take a trip below the sink with Marta in this top-down 2D shooter through randomly generated mazes of pipes. Defeat gooey enemies, overcome strong bosses, and learn what\'s really going on when trouble starts brewing beneath our tubs and under our streets.',
      '<a href="https://store.steampowered.com/app/811320" target="_blank">Jupiter Hell</a></br></br>Jupiter Hell is a turn-based shooter from the depths of cosmic hell, built on a classic roguelike framework updated with modern 3d graphics. Rip and tear zombies, demons, and heavy metal monstrosities with chainguns and chainsaws. Like chess... with shotguns!',
      '<a href="https://store.steampowered.com/app/1970580" target="_blank">Backpack Hero</a></br></br>The inventory management roguelike! Collect rare items, organize your bag, and vanquish your foes!',
      '<a href="https://store.steampowered.com/app/1109170" target="_blank">Happy Grumps</a></br></br>Happy Grumps is a love letter to classic roguelike adventures with a twist. Instead of trying to steal treasure or fight monsters, you are on a quest to spread happiness to a grumpy world.',
      '<a href="https://store.steampowered.com/app/1769170" target="_blank">Shattered Pixel Dungeon</a></br></br>Shattered Pixel Dungeon is a traditional roguelike dungeon crawler that\'s simple to start but hard to master! Every game is a unique challenge, with four different heroes, randomized levels and enemies, and hundreds of items to collect and use.',
      '<a href="https://store.steampowered.com/app/418530" target="_blank">Spelunky 2</a></br></br>Spelunky 2 builds upon the unique, randomized challenges that made the original a roguelike classic, offering a huge adventure designed to satisfy players old and new. Meet the next generation of explorers as they find themselves on the Moon, searching for treasure and missing family.',
      '<a href="https://store.steampowered.com/app/320040" target="_blank">Moon Hunters</a></br></br>Play alone or with friends! A co-op personality test about exploring an ancient, occult world in 5 days. How will you be remembered?',
      '<a href="https://store.steampowered.com/app/1963900" target="_blank">Knotwords</a></br></br>Knotwords is a minimal and elegant logic puzzle — with words. Arrange each section so every word across and down is valid. It may look difficult at first, but you\'ll be surprised at how quickly you pick it up! This is the kind of game I\'ve been trying to design my whole career — I hope you like it',
      '<a href="https://store.steampowered.com/app/528230" target="_blank">SYNTHETIK: Legion Rising</a></br></br>SYNTHETIK is an unforgiving tactical shooter rogue-lite where freedom and experimentation is key. Fight in a world overrun by the Machine Legion and their Gods. Experience the next level in gun-play and dive into unparalleled build options and Android upgrades. Can you defeat the Heart of Armageddon?',
      '<a href="https://store.steampowered.com/app/1582380" target="_blank">Midautumn</a></br></br>Crashing at Grandma\'s was meant to be a break from your responsibilities. But relaxing might prove hard when the Spirit World is real, its entrance is in your basement, and you\'re its newest guardian. Blast evil spirits and save your hometown in this rogue-like dungeon crawler!',
      '<a href="https://store.steampowered.com/app/1603590" target="_blank">My Cousin the Rogue</a></br></br>A simple traditional roguelike with ASCII art where you save the monsters instead of hurting them.',
      '<a href="https://store.steampowered.com/app/551620" target="_blank">Approaching Infinity</a></br></br>Explore an infinite procedural universe in this turn-based, tile-based, open-world, hyphen-ated, sci-fi rogue-like RPG influenced by the classics of the genre. 17 factions strive for dominance, survival, or redemption in this hostile galaxy. Can you survive long enough to make a difference?',
      '<a href="https://store.steampowered.com/app/497800" target="_blank">Golden Krone Hotel</a></br></br>Golden Krone Hotel is a gothic horror roguelike. Fight vampires with sunlight or become a vampire yourself and sneak in the shadows. Combines classic turn-based combat with dynamic lighting, an innovative potion system, and fast paced gameplay.',
      '<a href="https://store.steampowered.com/app/329970" target="_blank">KeeperRL</a></br></br>Ambitious dungeon simulator with roguelike and RPG elements. Take the role of an evil wizard and study the methods of black magic. Equip your minions and explore the world, murder innocent villagers and burn their homes. Build your dungeon, lay traps and prepare for an assault of angry heroes.',
      '<a href="https://store.steampowered.com/app/2083840" target="_blank">Her Name Was Fire</a></br></br>Her Name Was Fire is a Tarotpunk twin stick roguelike with deck building elements where you progressively unlock spells and upgrades to defeat hordes of void creatures. Survive the 5 stages of grief and vanquish the Major Allegories.',
      '<a href="https://store.steampowered.com/app/1097530" target="_blank">Mortal Glory</a></br></br>Mortal Glory is a fantasy-themed tactical roguelike game about recruiting a team of gladiators and pitting them against brutal competition in a blood-soaked tournament. Train your gladiators, find a legendary sword, learn ancient spells, recruit a celebrity, cheat - do whatever it takes to bring glory to your name!',
      '<a href="https://store.steampowered.com/app/1681840" target="_blank">Summoners Fate</a></br></br>Summoners Fate is a roguelike adventure that fuses traditional turn-based combat with tactical card combat. Set in the fantasy land known as the Multiverse, you\'re tasked with guiding summoners through perilous quests in search of hidden secrets, powerful cards, and mutated rabbits.',
      '<a href="https://store.steampowered.com/app/1029210" target="_blank">30XX</a></br></br>Jump, shoot, and slash your way through 30XX, the roguelike action platformer you can play with a friend! Explore lush, ever-changing worlds that mix precise platforming with fevered combat. Destroy fearsome Guardians. Master unique Powers. Rediscover the thousand years we\'ve lost.',
      '<a href="https://store.steampowered.com/app/1062810" target="_blank">Inkbound</a></br></br>Go on co-op adventures in Inkbound, an online roguelike from the creators of Monster Train. Craft powerful character builds in procedurally generated runs and battle your way past the inky hordes with a unique active battle system.',
      '<a href="https://store.steampowered.com/app/458330" target="_blank">Vilmonic</a></br></br>Vilmonic is an artificial life simulator and genetics and evolution sandbox game. Protect and breed unique pixel-art life forms where pixels and color have meaning. Craft tools and buildings and change the environment. Find ancient tech and fend off haywire zombitons. Craft Farm Breed Evolve!',
      '<a href="https://store.steampowered.com/app/1095040" target="_blank">Unexplored 2: The Wayfarer\'s Legacy</a></br></br>Unexplored 2: The Wayfarer’s Legacy is a deep, slow-paced, immersive, open-world rogueRPG, with a table-top \'feel\' &amp; a cool twist on permadeath.',
      '<a href="https://store.steampowered.com/app/1343460" target="_blank">Selenwald</a></br></br>Selenwald is an action roguelike RPG that combines challenging combat with strategy and resource management. Take control of random adventurers to fight and sneak your way through eldritch horrors roaming the ever changing halls of Selenwald university.',
      '<a href="https://store.steampowered.com/app/603960" target="_blank">Monolith</a></br></br>Monolith is a top down action shooter with procedurally generated elements. Explore a large, abandoned facility in search of incredible power, fighting dangerous foes and gaining new weapons and upgrades as you progress.',
      '<a href="https://store.steampowered.com/app/881100" target="_blank">Noita</a></br></br>Noita is a magical action roguelite set in a world where every pixel is physically simulated. Fight, explore, melt, burn, freeze and evaporate your way through the procedurally generated world using spells you\'ve created yourself.',
      '<a href="https://store.steampowered.com/app/975370" target="_blank">Dwarf Fortress</a></br></br>The deepest, most intricate simulation of a world that\'s ever been created. The legendary Dwarf Fortress is now on Steam. Build a fortress and try to help your dwarves survive against a deeply generated world.',
      '<a href="https://store.steampowered.com/app/1673090" target="_blank">Vagabond</a></br></br>Explore procedurally generated living worlds in this 2D sandbox RPG. Meet hundreds of characters in cities, complete quests, craft powerful items, buy and furnish your home or fight monsters in dungeons.',
      '<a href="https://store.steampowered.com/app/1410140" target="_blank">Load Roll Die</a></br></br>Stop, swap and roll your dice in this Roguelite Dice-builder! Steal dice faces from your enemies and use them to create the perfect dice set for taking down your opponents. Roll and combine your dice to create explosions, freeze faces, duplicate dice and more!',
      '<a href="https://store.steampowered.com/app/1296610" target="_blank">Peglin</a></br></br>Peglin is a Pachinko Roguelike - Fight enemies by collecting special orbs and popping pegs to deal damage. Acquire special relics that radically change the game and ensure no two runs are the same. Aim carefully to survive in this unique turn-based RPG!',
      '<a href="https://store.steampowered.com/app/1288540" target="_blank">Jupiter Moons: Mecha🦾</a></br></br>Choose your mech, customize your loadout, and build your perfect deck. Experiment with cards to find powerful combinations as you enjoy the tactical combat and deckbuilding in this roguelike adventure!',
      '<a href="https://store.steampowered.com/app/1639080" target="_blank">Sandwalkers</a></br></br>Sandwalkers is a roguelike turn-based exploration game. Build your team, traverse varied hostile environments, face countless dangers, and gain knowledge that will help you find and resurrect the Mother Tree Umama.',
      '<a href="https://store.steampowered.com/app/1776930" target="_blank">Undergrave</a></br></br>Undergrave is a tactical roguelike in which moving, jumping, managing your stamina, dashing and 𝘁𝗵𝗿𝗼𝘄𝗶𝗻𝗴 𝘆𝗼𝘂𝗿 𝘀𝘄𝗼𝗿𝗱 𝗮𝘄𝗮𝘆 strategically is vital for success.',
      '<a href="https://store.steampowered.com/app/1370940" target="_blank">NovaMundi</a></br></br>NovaMundi is a procedural exploration RPG with survival elements in which you lead a group of native warriors and explorers who traverse the vast and dangerous territories of the Andean mountains, seeking to unite the Muisca populations against the first wave of Spanish invaders in the XVI century.',
      '<a href="https://store.steampowered.com/app/1167680" target="_blank">Orbital Bullet – The 360° Rogue-lite</a></br></br>Orbital Bullet is a fast paced 360° action-platformer with rogue-lite elements, where all actions take place in a circular pattern. Fight your way through a variety of procedural planets and use body modifications, crafting and heavy weaponry. Kill. Die. Modify.',
      '<a href="https://store.steampowered.com/app/628770" target="_blank">Tangledeep</a></br></br>Enter the magical world of Tangledeep, a beautifully polished dungeon crawler inspired by classic 16-bit RPGs! Colorful characters, a unique job system, tons of skills, items, and diverse environments with deep, turn-based roguelike gameplay. A different adventure every time you play!',
      '<a href="https://store.steampowered.com/app/342610" target="_blank">HyperRogue</a></br></br>A tactical puzzle/roguelike on a hyperbolic plane.',
      '<a href="https://store.steampowered.com/app/259680" target="_blank">Tales of Maj\'Eyal</a></br></br>Tales of Maj’Eyal is a roguelike RPG, featuring tactical turn-based combat and advanced character building. Play as one of many unique races and classes in the lore-filled world of Eyal, exploring random dungeons, facing challenging battles, and developing characters with your own tailored mix of abilities and powers.',
      '<a href="https://store.steampowered.com/app/861540" target="_blank">Dicey Dungeons</a></br></br>Become a giant walking dice, explore dungeons and defy Lady Luck in this dice powered roguelike! Now featuring &quot;Reunion&quot;, a free DLC with six brand-new episodes!',
      '<a href="https://store.steampowered.com/app/1940340" target="_blank">Darkest Dungeon® II</a></br></br>Darkest Dungeon II is a roguelike road trip of the damned. Form a party, equip your stagecoach, and set off across the decaying landscape on a last gasp quest to avert the apocalypse. The greatest dangers you face, however, may come from within...',
      '<a href="https://store.steampowered.com/app/603390" target="_blank">Stone Story RPG</a></br></br>An auto-RPG with strategic combat, deep crafting and programming elements, animated entirely in ASCII-art. In a realm of perpetual darkness, a single stone could change everything...',
      '<a href="https://store.steampowered.com/app/258070" target="_blank">Probability 0</a></br></br>Never reach the bottom of the pit that is Probability 0. The game is different every time you die: the enemies you fight, the landscape you climb down, and the body you inhabit (if you so choose). Never survive. But find your way deeper than you did last time.'
    ]
  })

  grammar.addModifiers(tracery.baseEngModifiers)
  return grammar.flatten('#origin#')
}
