import tracery from 'tracery-grammar'

export const actionString = (game: string) => {
  return `Phwoop! A capsule shoots out of the tube! Unfurling the paper inside, it reads: ${game}.`
}

export const generate = () => {
  var grammar = tracery.createGrammar({
    origin: ['<a href="https://store.steampowered.com/app/364510" target="_blank">Transcendence</a></br></br>Explore the farthest reaches of Human Space in this open-world space adventure. Compelled to journey to the Galactic Core by a mysterious hyperintelligence, you must fight your way through dozens of star systems teeming with clashing empires, expansionist AIs, and fearsome xenophobes.',
      '<a href="https://store.steampowered.com/app/497800" target="_blank">Golden Krone Hotel</a></br></br>Golden Krone Hotel is a gothic horror roguelike. Fight vampires with sunlight or become a vampire yourself and sneak in the shadows. Combines classic turn-based combat with dynamic lighting, an innovative potion system, and fast paced gameplay.',
      '<a href="https://store.steampowered.com/app/258070" target="_blank">Probability 0</a></br></br>Never reach the bottom of the pit that is Probability 0. The game is different every time you die: the enemies you fight, the landscape you climb down, and the body you inhabit (if you so choose). Never survive. But find your way deeper than you did last time.',
      '<a href="https://store.steampowered.com/app/1422190" target="_blank">Fuzz Force: Spook Squad</a></br></br>Roll into a dicey deckbuilder set in a spooky board game world. Capture ghosts as the elite Spook Squad using their customisable Dice-Powered weaponry. Navigate eerie areas filled with battles, treasure and random events on your mission to capture the ghoulish PolterPrince.',
      '<a href="https://store.steampowered.com/app/1109170" target="_blank">Happy Grumps</a></br></br>Happy Grumps is a love letter to classic roguelike adventures with a twist. Instead of trying to steal treasure or fight monsters, you are on a quest to spread happiness to a grumpy world.',
      '<a href="https://store.steampowered.com/app/1296610" target="_blank">Peglin</a></br></br>Peglin is a Pachinko Roguelike - Fight enemies by collecting special orbs and popping pegs to deal damage. Acquire special relics that radically change the game and ensure no two runs are the same. Aim carefully to survive in this unique turn-based RPG!',
      '<a href="https://store.steampowered.com/app/848030" target="_blank">Roundguard</a></br></br>Roundguard is a bouncy dungeon crawler with pinball physics, lots of loot, and a randomized castle full of oddballs. Press your luck against hordes of dangerously cute monsters and challenging roguelike elements in this all-round bouncy adventure!',
      '<a href="https://store.steampowered.com/app/333640" target="_blank">Caves of Qud</a></br></br>Caves of Qud is a science fantasy roguelike epic steeped in retrofuturism, deep simulation, and swathes of sentient plants. Come inhabit an exotic world and chisel through layers of thousand-year-old civilizations.',
      '<a href="https://store.steampowered.com/app/311720" target="_blank">Sproggiwood</a></br></br>Bring civilization to Sproggiwood, a story-driven, turn-based roguelike set in a humorous world inspired by Finnish mythology. Grow your civilization and plunder procedural dungeons with six unique classes. Outsmart mischievous monsters who work together in unexpected ways. No two dungeon dives are alike.',
      '<a href="https://store.steampowered.com/app/1102190" target="_blank">Monster Train</a></br></br>Monster Train is a strategic roguelike deck building game with a twist. Set on a train to hell, you’ll use tactical decision making to defend multiple vertical battlegrounds. With real time competitive multiplayer and endless replayability, Monster Train is always on time.',
      '<a href="https://store.steampowered.com/app/628770" target="_blank">Tangledeep</a></br></br>Enter the magical world of Tangledeep, a beautifully polished dungeon crawler inspired by classic 16-bit RPGs! Colorful characters, a unique job system, tons of skills, items, and diverse environments with deep, turn-based roguelike gameplay. A different adventure every time you play!',
      '<a href="https://store.steampowered.com/app/1271280" target="_blank">Rift Wizard</a></br></br>Rift Wizard is a tough as nails fantasy roguelike featuring challenging turn based combat and deep open ended character building. Craft your spellbook from over 100 unique spells and abilities and fight your way through a series of procedurally generated challenges to defeat your nemesis.',
      '<a href="https://store.steampowered.com/app/881100" target="_blank">Noita</a></br></br>Noita is a magical action roguelite set in a world where every pixel is physically simulated. Fight, explore, melt, burn, freeze and evaporate your way through the procedurally generated world using spells you\'ve created yourself.',
      '<a href="https://store.steampowered.com/app/212680" target="_blank">FTL: Faster Than Light</a></br></br>This "spaceship simulation roguelike-like" allows you to take your ship and crew on an adventure through a randomly generated galaxy filled with glory and bitter defeat.',
      '<a href="https://store.steampowered.com/app/590380" target="_blank">Into the Breach</a></br></br>Control powerful mechs from the future to defeat an alien threat. Each attempt to save the world presents a new randomly generated challenge in this turn-based strategy game.',
      '<a href="https://store.steampowered.com/app/1304770" target="_blank">The Magister</a></br></br>The Magister is a murder-mystery card-battler RPG. Build and customise your deck to fight in battles, or use ‘Tactical Diplomacy’ to pacify those who stand in your way. Gather clues and discover motives as you investigate the death of your predecessor and unmask the guilty culprit.',
      '<a href="https://store.steampowered.com/app/1304780" target="_blank">Nongunz: Doppelganger Edition</a></br></br>Nongunz is a roguelite action-platformer. Battle grotesque creatures, kill quickly to maintain your combo meter, and rescue worshipers to become part of your idle army to buy upgrades.',
      '<a href="https://store.steampowered.com/app/1361840" target="_blank">Tunnel of Doom</a></br></br>Tunnel of Doom is an action rogue-lite hybrid that mixes tower defense with melee and ranged combat gameplay. Randomly generated, every run is different as you guide Angel on a quest to rescue her husband. Gather resources, discover perks, and use what you find to battle waves of monsters.',
      '<a href="https://store.steampowered.com/app/1095040" target="_blank">Unexplored 2: The Wayfarer\'s Legacy</a></br></br>Unexplored 2: The Wayfarer’s Legacy is a challenging roguelite RPG, with a table-top \'feel\', a node-based open world & cool twist on permadeath.',
      '<a href="https://store.steampowered.com/app/943590" target="_blank">BlitzKeep Unleashed</a></br></br>BlitzKeep Unleashed, where billiards meets a roguelite RPG! Or maybe pinball meets an RPG? Something like that! Level up, defeat enemies and bosses, buy permanent upgrades and new classes, play local coop, and more in procedurally-generated dungeons across 10 realms and 40 levels.',
      '<a href="https://store.steampowered.com/app/1769170" target="_blank">Shattered Pixel Dungeon</a></br></br>Shattered Pixel Dungeon is a Roguelike Dungeon Crawler RPG, originally for Android, with pixel art graphics. Every game is a unique challenge, with four different playable characters, randomized levels and enemies, and hundreds of items to collect and use. The game is simple to get into, but strategy is required if you want to win!',
      '<a href="https://store.steampowered.com/app/288120" target="_blank">Dungeonmans</a></br></br>Crush monsters and get loots in the classic turn-based style of deep dungeons and high adventure! Grow the Dungeonmans Academy, a bastion of learning that expands as you play. Serious gameplay with a light-hearted atmosphere, combining the feel of history\'s great RPGs and dice-slinging adventures around the tabletop.',
      '<a href="https://store.steampowered.com/app/379210" target="_blank">Wayward</a></br></br>You awake to discover yourself no longer in the company of good men or a fine seafaring vessel. Treasure... you remember something about treasure. Wayward is a challenging turn-based, top-down, wilderness survival roguelike. Explore, build, and most importantly survive in these unforgiving lands.',
      '<a href="https://store.steampowered.com/app/259680" target="_blank">Tales of Maj\'Eyal</a></br></br>Tales of Maj’Eyal is a roguelike RPG, featuring tactical turn-based combat and advanced character building. Play as one of many unique races and classes in the lore-filled world of Eyal, exploring random dungeons, facing challenging battles, and developing characters with your own tailored mix of abilities and powers.',
      '<a href="https://store.steampowered.com/app/372080" target="_blank">Ananias Roguelike</a></br></br>Explore five ancient realms fighting their monstrous inhabitants in this turn based, graphical classic roguelike. Every time you play the game will create new places full of challenges and surprises for you populated with monsters and ancient magical artifacts.',
      '<a href="https://store.steampowered.com/app/1370940" target="_blank">NovaMundi: The Spear of Chaquén</a></br></br>NovaMundi: The Spear of Chaquén is an open-world RPG roguelike in which you lead a group of indigenous explorers and warriors making their way through vast and dangerous territories in the Andes, seeking to unite the Muisca populations against the first wave of Spanish invaders in the XVI century.',
      '<a href="https://store.steampowered.com/app/270050" target="_blank">Quest of Dungeons</a></br></br>Quest of Dungeons is a turn based dungeon crawler game featuring a good old 16-bit retro artistic look. By playing as either a Warrior, Wizard, Assassin or Shaman you have to traverse dungeons, defeat enemies and loot everything you can in order to survive.',
      '<a href="https://store.steampowered.com/app/342610" target="_blank">HyperRogue</a></br></br>A tactical puzzle/roguelike on a hyperbolic plane.',
      '<a href="https://store.steampowered.com/app/432380" target="_blank">Hydra Slayer</a></br></br>roguelike based on mathematical puzzles',
      '<a href="https://store.steampowered.com/app/603390" target="_blank">Stone Story RPG</a></br></br>An auto-RPG with strategic combat, deep crafting and programming elements, animated entirely in ASCII-art. In a realm of perpetual darkness, a single stone could change everything...',
      '<a href="https://store.steampowered.com/app/561740" target="_blank">MidBoss</a></br></br>Kill your enemies, possess their bodies, and take their abilities as your own in this turn-based procedurally generated death labyrinth.',
      '<a href="https://store.steampowered.com/app/329970" target="_blank">KeeperRL</a></br></br>Ambitious dungeon simulator with roguelike and RPG elements. Take the role of an evil wizard and study the methods of black magic. Equip your minions and explore the world, murder innocent villagers and burn their homes. Build your dungeon, lay traps and prepare for an assault of angry heroes.',
      '<a href="https://store.steampowered.com/app/1266820" target="_blank">Ultimate ADOM - Caverns of Chaos</a></br></br>Experience the sequel of the traditional roguelike dungeon-crawling classic. Enjoy unlimited replayability through endless procedurally generated dungeons, countless monsters, grafting, crafting and a vast amount of skill trees. Journey into the ever changing depths of the Caverns of Chaos.',
      '<a href="https://store.steampowered.com/app/1167680" target="_blank">Orbital Bullet – The 360° Rogue-lite</a></br></br>Orbital Bullet is a fast paced 360° action-platformer with rogue-lite elements, where all actions take place in a circular pattern. Fight your way through a variety of procedural planets and use body modifications, crafting and heavy weaponry. Kill. Die. Modify.',
      '<a href="https://store.steampowered.com/app/740080" target="_blank">Deadly Days</a></br></br>Deadly Days is a unique strategic rogue-lite in the zombie apocalypse. Manage and protect a group of survivors and help them to stop the catastrophe. Discover and use a large number of wild and crazy objects, even wilder and crazier survivors, special abilities, and deadly weapons.',
      '<a href="https://store.steampowered.com/app/333300" target="_blank">ADOM (Ancient Domains Of Mystery)</a></br></br>ADOM (Ancient Domains Of Mystery) is one of the most successful roguelike games ever created, boasting a brilliant mix of story, RPG, exploration, and intensely strategic and flexible combat. The Steam version adds various Deluxe features like achievements, difficulty level customization and various play modes (e.g.',
      '<a href="https://store.steampowered.com/app/646570" target="_blank">Slay the Spire</a></br></br>We fused card games and roguelikes together to make the best single player deckbuilder we could. Craft a unique deck, encounter bizarre creatures, discover relics of immense power, and Slay the Spire!',
      '<a href="https://store.steampowered.com/app/418530" target="_blank">Spelunky 2</a></br></br>Spelunky 2 builds upon the unique, randomized challenges that made the original a roguelike classic, offering a huge adventure designed to satisfy players old and new. Meet the next generation of explorers as they find themselves on the Moon, searching for treasure and missing family.',
      '<a href="https://store.steampowered.com/app/274700" target="_blank">868-HACK</a></br></br>You are a computer hacker. You steal precious data while the world sleeps.',
      '<a href="https://store.steampowered.com/app/254320" target="_blank">Duskers</a></br></br>Pilot drones into derelict spaceships to find the means to survive and piece together how the universe became a giant graveyard.',
      '<a href="https://store.steampowered.com/app/226620" target="_blank">Desktop Dungeons</a></br></br>FREE GAME UPDATE! Desktop Dungeons: Enhanced Edition. More ways to die horribly in 10 minutes or less. The award winning quick-play puzzle roguelike is now packed with new content, new classes and a new way to play: Compete against your friends in the seeded Daily Dungeon!',
      '<a href="https://store.steampowered.com/app/674930" target="_blank">Boyfriend Dungeon</a></br></br>Date your weapons! Romance swords, daggers, and polearms to level them up in this “shack-and-slash” dungeon crawling adventure.',
      '<a href="https://store.steampowered.com/app/320040" target="_blank">Moon Hunters</a></br></br>Play alone or with friends! A co-op personality test about exploring an ancient, occult world in 5 days. How will you be remembered?',
      '<a href="https://store.steampowered.com/app/501320" target="_blank">The Shrouded Isle</a></br></br>Includes the Sunken Sins free DLC! Your Excellency, in this short game, we prepare for the awakening of our Lord. He hungers for human sacrifice. Sinners try to hide their dark secrets, but all must be purged...',
      '<a href="https://store.steampowered.com/app/603960" target="_blank">Monolith</a></br></br>Monolith is a top down action shooter with procedurally generated elements. Explore a large, abandoned facility in search of incredible power, fighting dangerous foes and gaining new weapons and upgrades as you progress.'
    ]
  })

  grammar.addModifiers(tracery.baseEngModifiers)
  return grammar.flatten('#origin#')
}
