/* eslint-disable quotes */

import tracery from 'tracery-grammar'

export const actionString = (popcorn: string) => {
  return `You eat a bag of ${popcorn}!`
}

export const generate = () => {
  var grammar = tracery.createGrammar({
    origin: [
      "#flavor# and #topping# popcorn"
    ],
    flavor: [
      'Bacon',
      'Sugar',
      'Cinnamon',
      'Thyme',
      'Oregano-Basil',
      'Hot Sauce',
      'Sriracha',
      'Salt',
      'Butter',
      'Honey',
      'Roasted Herb',
      'English Mustard',
      'Wasabi',
      'Paprika',
      'Za’atar',
      'Banilla',
      'Blue Raspberry',
      'BBQ Sauce',
      'Brown Butter',
      'Garam Masala',
      'Curry',
      'Thai Pepper',
      'Natto',
      'Brine',
      'Nacho Cheese',
      'Honey Mustard',
      'Banana Ketchup',
      'Matcha',
      'Smoked Salt',
      'Angostura',
      'Guacamole',
      'Tajin',
      'Mangonada',
      'Chamoy',
      'Salt & Vinegar',
      'Salt & Vinereaper',
      'Dilute Salt Water',
      'Green Slime',
      'Ochre Jelly',
      'Absinthe',
      'Blackcurrant',
      'Vinewafer',
      'Marinara',
      'Strawberry',
      'Black Tea',
      'Ketchup',
      'Pumpkin Spice',
      'Moss',
      'Tonka Bean',
      'Mint',
      'Rose',
      'Pomegranate',
      'Quince',
      'Mayonnaise',
      'Ranch',
      'Chocolate',
      'Durian',
      'Persimmon',
      'Seasalt',
      'Gochujang',
      'Blood',
      'Melon',
      'Soy Sauce',
      'Milk',
      'Milk Tea',
      'Sea Urchin',
      'Geoduck',
      'Cherry Blossom',
      'Chestnut',
      'Pumpkin',
      'Fig',
      'Sweet Potato',
      'Osmanthus',
      'Saffron',
	  'Porcupine'
	  
    ],
    topping: [
      'Gummi Bear',
      'Gummi Worm',
      'Gummi Orb',
      'Gummi Eel',
      'Gummi Mimic',
      'Cookie',
      'Pretzel',
      'Nutritional Yeast',
      'Sprinkle',
      'Almond',
      'Cheese',
      'Raisin',
      'Kale',
      'Dill Pickle',
      'Sour Patch Kid',
      'Salt Licorice',
      'Furu',
      'Caramel',
      'Fudge',
      'Kimchi',
      'Cabbage',
      'Radish',
      'Raddichio',
      'Arugula',
      'Bok Choi',
      'Turnip',
      'Brussels Sprout',
      'Horseradish',
      'Broccoli',
      'Cauliflower',
      'Rutabaga',
      'Kohlrabi',
      'Collard Greens',
      'Gummi Steak',
      'Peanut',
      'Raisin',
      'Cashew',
      'Brazil Nut',
      'Cocoa Nib',
      'Coleslaw',
      'Mini Chip',
      'Cheese Puff',
      'Rice Cracker',
      'Wheatabix',
      'Pecan Praline',
      'Flintstone Kids Vitamin',
      'GORP',
      'Chili Crisp',
      'Fried Onions',
      'Edamame',
      'Chorizo',
      'Sprinkles of Zot',
      'Fudge of Yendor',
      'Gummi Cockatrice',
      '10,000 Pieces of Oatmeal',
      'Banana Chip',
      'Furikake',
      'MSG',
      'Whipped Cream',
      'Protein Powder',
      'Dried Squid',
      'Dried Cricket',
      'Circus Peanut',
      'Candy Corn',
      'Shredded Clown',
      'Soylent Green',
      'Mulberry Leaf',
      'Quinoa',
      'Gummi Goo',
      'Pemmican',
      'Poppyseed',
      'Gold Leaf',
      'Peppercorn',
      'Bonito Flake',
      'Roe',
      'Spinach',
      'Sesame Seed',
      'Pepita',
      'Cherry',
      'Maple Sugar',
      'Magic Bean',
      'Sunshine',
      'Lotus Paste',
      'Egg',
      'Cockatrice Egg',
      'Boba'
    ]
  })

  grammar.addModifiers(tracery.baseEngModifiers)
  return grammar.flatten('#origin#')
}
/* eslint-enable quotes */
