/* eslint-disable quotes */

import tracery from 'tracery-grammar'

export const actionString = (veganFood: string) => {
  return `You eat a ${veganFood}.`
}

export const generate = () => {
  var grammar = tracery.createGrammar({
    origin: [
      "delicious bowl of #fruit# and #plant# with #powerup# sauce",
      "bowl of #plant# and #protein#"
    ],
    fruit: [
      'apple',
      'kiwi',
      'grape',
      'pear',
      'blackberry',
      'blueberry',
      'sunberry',
      'raspberry',
      'salmonberry',
      'nectarine',
      'peach',
      'pineapple',
      'passionfruit',
      'tomato',
      'sundried tomato',
      'dried banana',
      'Dried apple',
      'elderberry',
      'plum',
      'musical fruit',
      'next level banana',
      'pepers',
      'oran berry',
      'apricorn',
      'devil fruit',
      'killer tomato',
      'ancient fruit',
      'strawberry',
      'lemon',
      'lime',
      'orange',
      'dragonfruit',
      'stinky durian',
      'lychee',
      'mango',
      'kumquat',
      'guava',
      'rambutan',
      'feijoa',
      'noni',
      'choko',
      'Gros Michel banana'
    ],
    powerup: [
      'blindness',
      'confusion',
      'detect monster',
      'detect things',
      'extra healing',
      'hallucination',
      'haste self',
      'healing',
      'increase strength',
      'levitation',
      'poison',
      'raise level',
      'restore strength',
      'see invisible',
      'intoxication',
      'fire breath',
      'brown',
      'red',
      'white',
      'blue',
      'green',
      'yellow',
      'purple',
      'orange',
      'obsidian',
      'deep',
      'whimsy goddess',
      'lord\'s wrath',
      'spicy',
      'lovely jubbly',
      'skullduggery',
      'occult',
      'permadeath',
      'procedural',
      'rogue light',
      'loose lips',
      'expensive',
      'love',
      'archeologist',
      'barbarian',
      'healer',
      'knight',
      'monk',
      'priestess',
      'ranger',
      'rogue',
      'samurai',
      'tourist',
      'valkyrie',
      'wizard',
      'meat',
      'mana',
      'superior mana',
      'gingerbread',
      'pumpkin spice',
      'sewer brew',
      'battle readiness',
      'copycat ability',
      'soft hair',
      'knowing labyrinths',
      'high rolls',
      'RNG',
      '100 sided',
      'stinky presence',
      'temporary charisma',
      'curse',
      'ice cream',
      'daisy',
      'lilac',
      'rose',
      'tulip',
      'charm',
      'INT seed',
      'AGL seed',
      'STAM seed',
      'LCK seed',
      'sexy',
      'mathematics',
      'vampire\'s thrall',
      'square',
      'triangle',
      'sphere',
      'cube',
      'icosahedron',
      'iron skin',
      'golden touch',
      'giant growth',
      'hyper',
      'lightfoot',
      'featherfall',
      'magic missile',
      'athleticism',
      'spider climb',
      'neurosis',
      'disco',
      'performance',
      'natural history',
      'beast hide',
      'rage',
      'fear',
      'sleeping',
      'paralysis',
      'dwarf skin',
      'ice breath',
      'lightning touch',
      'necro',
      'raise dead',
      'escape rope',
      'stone gaze',
      'reflect',
      'barrier',
      'thorns aura',
      'water breathing',
      'luck',
      'fortune',
      'destiny',
      'foresight',
      'death',
      'instant death',
      'multiplayer',
      'call for help',
      'increase ability',
      'ability point',
      '+1',
      'fortitude',
      'mental fortitude',
      'stealth',
      'cloaking',
      'cacophony',
      'endurance',
      'polymorph',
      'swimming',
      'autosave',
      'rage quit',
      'session scheduling',
      'bludgeoning',
      'piercing',
      'shadow',
      'blessings',
      'angelic favor',
      'demonic favor',
      'dimensional travel',
      'avatar form',
      'force',
      'speak with animals',
      'truth',
      'nocturnal',
      'pickpocket',
      'intimidation',
      'invisibility',
      'trance',
      'mystic bond',
      'moon',
      'sun',
      'deep sea',
      'wanderlust',
      'royalty',
      'street urchin',
      'disguise',
      'poisoned kiss',
      'quenching',
      'doom',
      'culture',
      'riddle',
      'pizza',
      'madness',
      'TinyMedal',
      'Estus',
      'comestible',
      'Bumpblade',
      'Unterzee',
      'fizzy lifting',
      'Heart of the Cards',
      'creepypasta'
    ],
    plant: [
      'pumpkin',
      'turnip',
      'rice',
      'potato',
      'ginger',
      'garlic',
      'scallions',
      'an unidentifiable protein',
      'tea leaves',
      'peppermint leaves',
      'catnip leaves',
      'pesto',
      'squash',
      'butternut squash',
      'root powder',
      'walnut',
      'pine nut',
      'pistachio',
      'almond',
      'saffron rice',
      'amaranth',
      'oats',
      'nut paste',
      'nut butter',
      'peanuts',
      'snap pea',
      'pea mash',
      'potato mash',
      'turnip mash',
      'pumpkin mash',
      'chili',
      'chili paste',
      'tomato paste',
      'white bean',
      'tapioca',
      'flax',
      'couscous',
      'cereal mix',
      'eggplant',
      'broccoli',
      'cauliflower',
      'jalapeno',
      'red pepper',
      'green pepper',
      'hawthorne salad',
      'arugula',
      'grits',
      'leek',
      'celery',
      'mixed Seed',
      'half moon grass',
      'peacebloom',
      'lemongrass',
      'quinoa',
      'chickpea',
      'burb root',
      'moss of mareilon',
      'spenseweed',
      'mandrake',
      'nopales',
      'yucca',
      'spinach',
      'kale',
      'seaweed',
      'slime mold',
      'vinewafer',
      'wild rice',
      'meterlong beans',
      'corn (or is it maize?)',
      'maize (or is it corn?)'
    ],
    protein: [
      'imitation #meat#',
      'tofu',
      'tempeh',
      'turtle beans', // shoutout to one of the weirder balatro jokers - kawa
      'sunflower seeds',
      'delicately spiced #plant#'
    ],
    meat: [
      'chicken',
      'beef',
      'pork',
      'turkey',
      'salmon',
      'tilapia',
      'Magikarp',
      'eel',
      'minotaur',
      'human'
    ]
  })

  grammar.addModifiers(tracery.baseEngModifiers)
  return grammar.flatten('#origin#')
}
/* eslint-enable quotes */
