export default [
  'Roguelike Celebration socks',
  'a +1 longbow',
  'an unidentified scroll',
  'a tiny puppy',
  'Platinum Yendorian Express Card',
  'a wand of digging',
  'a Proof of Stremf',
  'a shotgun',
  'a pair of seven league boots',
  'Planepacked',
  'Divine Nectar',
  'the Fizzbuzz',
  'Yet Another Silly Drink',
  'Orb of Zot',
  'Amulet of Yendor',
  'box of crayons',
  'lemonade',
  'slightly stale cookies',
  'negasocks',
  'negalongbow',
  'healing scroll',
  'negapuppy',
  'Her-yell, Goblin Knife-Princess',
  'Mr Stabbums, Battle Kitty',
  'Ooze, Faithful Sidekick',
  'Roguelike Celebration Shower Curtain',
  'a mystic dagger',
  'a pet eel'
]
