export interface RoomNote {
    // UUID generated by the client
    id: string

    // The plaintext message of the note
    message: string

    // user ID
    authorId: string

    // Array of user IDs
    likes?: string[]
}
