name: Production Build and Deploy

on: workflow_dispatch

jobs:
  build-and-deploy:
    uses: ./.github/workflows/deploy.yml
    secrets:
      SERVER_HOSTNAME: ${{ secrets.SERVER_HOSTNAME }}
      AZURE_FUNCTION_APP_NAME: ${{ secrets.AZURE_FUNCTION_APP_NAME }}
      AZURE_FUNCTIONAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
      DEPLOY_WEBHOOK_KEY: ${{ secrets.DEPLOY_WEBHOOK_KEY }}
      ASWA_API_TOKEN: ${{secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
